#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import argparse
from neovim import socket_session, Nvim

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="NeoVim TeX client")
    parser.add_argument('--addr', default='/tmp/nvim_tex.sock',
                        help="NeoVim listen address")
    parser.add_argument('file', help="file")
    parser.add_argument('line', type=int, help="line")
    parser.add_argument('column', type=int, default=0, help="column")
    args = parser.parse_args()

    session = socket_session(args.addr)
    nvim = Nvim.from_session(session)

    for win in nvim.windows:
        name = win.buffer.name
        if os.path.isfile(name) and os.path.samefile(name, args.file):
            nvim.current.window = win
            break
    else:
        nvim.command("tabe {}".format(args.file))

    nvim.current.window.cursor = (args.line, args.column)

# vim: ts=4 sts=4 sw=4 expandtab
